services:
  db_sortedor_estudantes:
    image: postgres
    container_name: db_sortedor_estudantes
    restart: always
    ports:
      - 5001:5432
    env_file:
      - .env.test

  node_sorteador_estudantes:
    container_name: node_sorteador_estudantes
    build: .
    ports: 
      - 5000:5000
    depends_on:
      - db_sortedor_estudantes
    env_file:
      - .env.test
